Zj1.6 about
michaljedro/zaplanujJedzonko pull request #10
Opened 2020-11-07 18:11 UTC by michaljedro

2020-11-16 18:24 UTC, pawel-schmidt requested changes
Please attach some screenshot of your work :-)

2020-11-16 18:24 UTC, pawel-schmidt commented on index.html
> +        <p class="">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptates aut adipisci officia fugit
Remove empty `class` attribute.

2020-11-16 23:05 UTC, pawel-schmidt requested changes

2020-11-16 23:05 UTC, pawel-schmidt commented on app/scss/_global.scss
> +.bgc_1 {
Names with a number suffix are a bad practice. There are of course some exceptions, but this one isn't one ;-)

2020-11-16 23:05 UTC, pawel-schmidt commented on app/scss/_global.scss
> +.bgc_1 {
Actually, is it used anywhere?

2020-11-19 22:48 UTC, michaljedro commented on index.html
> +        <p class="">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptates aut adipisci officia fugit
Removed ;)

2020-11-19 22:49 UTC, michaljedro commented on app/scss/_global.scss
> +    border: 1px solid orange;
Pardon

2020-11-19 22:54 UTC, michaljedro commented on app/scss/_global.scss
> +.bgc_1 {
i used once. I decided to add this class after our conversation in Warsaw. I supose to used as a class with background color.

2020-11-19 22:55 UTC, michaljedro commented on app/scss/_global.scss
> +.bgc_1 {
i think, the best way would be to remove it and use scss $ sign.

2020-11-20 13:15 UTC, michaljedro commented on app/scss/_global.scss
> +.bgc_1 {
ok. i think that class bgc_1 is not necessary.

2020-12-02 13:27 UTC, pawel-schmidt approved these changes

2020-12-02 19:08 UTC, merged