begin of ZJ1.7_branch
michaljedro/zaplanujJedzonko pull request #11
Opened 2020-11-07 18:12 UTC by michaljedro

2020-11-16 23:26 UTC, pawel-schmidt requested changes

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +        min-width: 25%;
Why not just `width: 25%`?

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +        background-color: #f09713;
Use SCSS variable here.

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +        color: #dc6121;
SCSS variable.

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +.bgc_1 {
`bgc_1` doesn't say much about this class. Can you find a better name?

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +.copyright {
This section also has `sans-serif` font.

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +    &__item-h3 {
Putting tag name in class name is tricky - when you change the tag, the name will be confusing. You may just use `item-header`.

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +        right: -11%;
Try to find another way to position the list.

2020-11-16 23:26 UTC, pawel-schmidt commented on app/scss/_footer.scss
> +        margin-left: 22px;
What would you do if the client asks about adding another icon? Will you add `&__item-sign:nth-of-type(4)` selector? 🤔

2020-11-16 23:26 UTC, pawel-schmidt commented on index.html
> +        <span class="copyright__text-modify"> Zaplanujjedzonko.pl</span>
Redundant space before `Zaplanuj` word.

2020-11-16 23:26 UTC, pawel-schmidt commented on index.html
> +        <div class="footer__item-ulcontainer">
Is this container actually necessary here?

2020-11-16 23:26 UTC, pawel-schmidt commented on index.html
> +        <br>
`<br>` tag should be used only in text tags like `p`, `h1`, `h2`, … - please add proper styles to add a space between sections.

2020-11-16 23:26 UTC, pawel-schmidt commented on index.html
> +    <div class="footer">
Why do not add `footer` class to `footer` element?

2020-11-20 14:42 UTC, michaljedro commented on app/scss/_footer.scss
> +        min-width: 25%;
i forgeto to remove it...

2020-11-20 14:44 UTC, michaljedro commented on app/scss/_footer.scss
> +        background-color: #f09713;
ok. i used $orangeColor fot it.

2020-11-20 14:45 UTC, michaljedro commented on app/scss/_footer.scss
> +        color: #dc6121;
done

2020-11-20 14:46 UTC, michaljedro commented on app/scss/_footer.scss
> +.bgc_1 {
i remove at all that from project

2020-11-20 14:47 UTC, michaljedro commented on app/scss/_footer.scss
> +.bgc_1 {
i guess i can used for it just style background-color with $grayColor.

2020-11-20 18:05 UTC, michaljedro commented on app/scss/_footer.scss
> +.copyright {
ok. done

2020-11-20 18:07 UTC, michaljedro commented on app/scss/_footer.scss
> +    &__item-h3 {
ok. i changed it to header

2020-12-01 21:46 UTC, michaljedro commented on app/scss/_footer.scss
> +        margin-left: 22px;
i know that method to select items in css

2020-12-01 21:51 UTC, michaljedro commented on index.html
> +        <span class="copyright__text-modify"> Zaplanujjedzonko.pl</span>
i remove space

2020-12-01 22:11 UTC, michaljedro commented on index.html
> +        <div class="footer__item-ulcontainer">
i used it to positioned in element.

2020-12-01 22:13 UTC, michaljedro commented on index.html
> +        <div class="footer__item-ulcontainer">
but it works without that too

2020-12-01 22:13 UTC, michaljedro commented on index.html
> +        <div class="footer__item-ulcontainer">
I remove it

2020-12-01 22:43 UTC, michaljedro commented on index.html
> +        <br>
ok. i remove it

2020-12-01 22:54 UTC, michaljedro commented on index.html
> +    <div class="footer">
ok. i changed it.

2020-12-02 13:32 UTC, pawel-schmidt approved these changes

2020-12-02 13:32 UTC, pawel-schmidt commented on app/scss/_colors.scss
> +$orangeColor: #f09713;
If client will ask you to change this color to green, you'll need to change the variable name. Better would be to name it like `primaryColor`. But let it be as is ;-)

2020-12-02 19:21 UTC, merged