Zj1.2/carousel section
michaljedro/zaplanujJedzonko pull request #5
Opened 2020-08-19 17:28 UTC by michaljedro

2020-09-01 20:00 UTC, michaljedro commented on app/js/script.js
> +var itemDiv = document.querySelectorAll('.slider div');
i did your suggestion

2020-09-01 20:02 UTC, michaljedro commented on app/js/script.js
> +console.log(btnPrev);
console.log removed

2020-09-01 20:14 UTC, michaljedro commented on app/js/script.js
> +var imagesCounter = 0;
i did it

2020-09-02 18:59 UTC, michaljedro commented on app/scss/_navigation.scss
> +    // padding: 10px 0;
done

2020-09-02 18:59 UTC, michaljedro commented on index.html
> +  <!-- <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet"> -->
done

2020-09-02 19:01 UTC, michaljedro commented on carusel.html
> +<!DOCTYPE html>
thats was added there by mistake

2020-09-02 19:35 UTC, michaljedro commented on app/scss/_carousel.scss
> +}
Done ;)

2020-09-03 19:13 UTC, pawel-schmidt requested changes

2020-09-03 19:13 UTC, pawel-schmidt commented on app/js/script.js
> +var item = Array.from(sliderDivs);
For arrays use plural form of noun for variables names. `items` is correct. At first glance you expect that `items` may contain more than one object.

2020-09-03 19:13 UTC, pawel-schmidt commented on app/scss/_carousel.scss
>  .slider div {
Use `.slider__text` instead of `div`.

2020-09-03 19:13 UTC, pawel-schmidt commented on app/scss/_carousel.scss
> +}
Here you use camel case naming - `nextPicture` - for CSS classes and in `app/scss/_navigation.scss` you use kebab case - `item-right`. Please decide which convention you want to use and stick to it. More popular IMO is kebab case in this case :-)

2020-09-03 19:13 UTC, pawel-schmidt commented on app/scss/_navigation.scss
> +header {
Don't use HTML tags to select. Please add class to the element and select it by class.

2020-09-03 19:13 UTC, pawel-schmidt commented on app/scss/_navigation.scss
> +  &__item-right ul {
To be honest here - and in the next selector - also class should be used to select.

2020-09-05 19:05 UTC, pawel-schmidt requested changes
Please fix the incorrect value.

2020-09-05 19:05 UTC, pawel-schmidt commented on app/scss/_navigation.scss
> +  &__item-right .list {
Your solution isn't wrong. I'm just showing you a nested solution. The result will be the same as yours.

```suggestion
  &__item-right .list {
    display: flex;
    width: 100%;
    height: 100%;
    justify-content: space-evenly;
    list-style-type: none;
    color: white;
    font-family: "Open Sans", sans-serif;
    &__items {
      height: 100%;
      display: table;
      &--modify {
        color: white;
        text-decoration: none;
        height: 100%;
        display: inline-block;
        vertical-align: middle;
        display: table-cell;
        &:hover {
          color: #e58a20;
        }
      }
    }
  }
```

2020-09-06 19:15 UTC, pawel-schmidt approved these changes

2020-09-06 19:16 UTC, merged