Zj1.3/call to action
michaljedro/zaplanujJedzonko pull request #6
Opened 2020-09-09 20:13 UTC by michaljedro

2020-09-10 19:08 UTC, pawel-schmidt requested changes

2020-09-10 19:08 UTC, pawel-schmidt commented on app/scss/_call-to-action.scss
> +        width: 60vw;
As above. There is a pattern you may follow to put an additional `div` into `.call-to-action` (let's add a `.call-to-action__wrapper` class to it) and the following styles:
```
.call-to-action__wrapper {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
```
`max-width` ensures the content is not wider than provided value. When the screen is narrower than provided value, wrapper will shrink.
`margin-x` centers the wrapper.

2020-09-10 19:08 UTC, pawel-schmidt commented on app/scss/_call-to-action.scss
> +        width: 60vw;
As above ☝️

2020-09-10 19:08 UTC, pawel-schmidt commented on app/scss/_call-to-action.scss
> +        width: 15vw;
As above ☝️

2020-09-13 12:34 UTC, michaljedro commented on index.html
> +      <a href="" class="call-to-action__advert--button-text">Lorem Ipsum</a>
ok. i missed up this

2020-09-13 12:57 UTC, michaljedro commented on app/scss/_call-to-action.scss
> +    height: 20vh;
ok. i changed it

2020-09-16 12:17 UTC, pawel-schmidt requested changes

2020-09-16 12:17 UTC, pawel-schmidt commented on app/scss/_call-to-action.scss
> +    & .call-to-action__wrapper {
Ampersand (`&`) is redundant here. In short, these both are working similarly:
```
.a {
  .b {
    color: white;
  }
}
```

```
.a {
  & .b {
    color: white;
  }
}
```
and will produce `.a .b { color: white; }`. Maybe you wanted to do it in this way:
```suggestion
&__wrapper {
```
?

2020-09-16 12:17 UTC, pawel-schmidt commented on app/scss/_call-to-action.scss
> +    & .call-to-action__advert {
As above ☝️  and as below 👇

2020-10-15 20:32 UTC, michaljedro commented on app/scss/_call-to-action.scss
> +        width: 60vw;
ok. i added it to my code

2020-10-15 20:50 UTC, michaljedro commented on app/scss/_call-to-action.scss
> +        width: 60vw;
i dont have got it in my code

2020-10-15 21:36 UTC, michaljedro commented on app/scss/_call-to-action.scss
> +        width: 15vw;
ok. i centered that with margin

2020-10-15 21:48 UTC, michaljedro commented on app/scss/_call-to-action.scss
> +    & .call-to-action__wrapper {
ok. i changed that

2020-10-15 21:49 UTC, michaljedro commented on app/scss/_call-to-action.scss
> +    & .call-to-action__advert {
changed

2020-10-16 22:52 UTC, pawel-schmidt approved these changes

2020-10-17 15:19 UTC, merged