Zj1.4/section offerts
michaljedro/zaplanujJedzonko pull request #7
Opened 2020-09-11 18:03 UTC by michaljedro

2020-09-16 20:40 UTC, pawel-schmidt requested changes

2020-09-16 20:40 UTC, pawel-schmidt commented on app/scss/_section-offerts.scss
> +.item-style {
Please find a better name for the class. To be honest this one is too general. Sometimes it's ok, for example for `column`, `row` (when you use grid), `container`, `wrapper` etc. Also, suffix `-style` is like `-class` and doesn't provide any useful information. Maybe try something like `.offers__offer` or `.offer__offer-item`?

2020-09-16 20:40 UTC, pawel-schmidt commented on app/scss/_section-offerts.scss
> +i {
Please do not use tags names in selectors. It's more than likely someone (maybe even you) in the future will use `i` element and get surprised why it's so big (in this way). Add some class here.

2020-09-16 20:40 UTC, pawel-schmidt commented on index.html
> +      <div class="item-style__icon">
There's no such `.item-style__icon` selector in CSS.

2020-09-16 20:40 UTC, pawel-schmidt commented on index.html
> +    <div class="section__offerts--items item-style">
Is this `item` or `items` regarding to the class names? 🤔

2020-10-16 09:32 UTC, michaljedro commented on app/scss/_call-to-action.scss
> +        letter-spacing: 0.1e nnb m;
ok. done

2020-10-16 10:52 UTC, michaljedro commented on app/scss/_section-offerts.scss
> +.item-style {
ok. i changed their names

2020-10-16 10:55 UTC, michaljedro commented on app/scss/_section-offerts.scss
> +i {
ok. i used the class for this

2020-10-16 11:35 UTC, michaljedro commented on app/scss/_section-offerts.scss
> +i {
the icon are from FontAwesome. I used the class convention applied in FA

2020-10-16 11:41 UTC, michaljedro commented on index.html
> +    <div class="section__offerts--items item-style">
ok. i removed the "item-style"

2020-10-16 23:06 UTC, pawel-schmidt commented on app/scss/_section-offerts.scss
> +i {
Better, but still not perfect. Imagine that you're ie. `fa-list` icon in another part of page. You'll be surprised that the icon is so big (`170px`) and in grey color. To avoid these type of unexpected behavior it's good to narrow selectors to point precisely particular element. In this case I'd use other class as a prefix, for example:
```
.section__offerts--items {
  …
  & .fas,
  & .far {
    font-size: 170px;
    color: gray;
  }
}
```
BTW I'm not sure if you are aware that FontAwesome gives a bunch of helper classes. One of them are use for icon size modification ([Sizing Icons](https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons)). Maybe it will be enough in your case?

2020-10-16 23:08 UTC, pawel-schmidt requested changes

2020-10-16 23:08 UTC, pawel-schmidt commented on app/scss/_section-offerts.scss
> +.fa-list {
I have written an answer in thread. Please fix this one and PR is ready to be merged :-)

2020-10-17 20:33 UTC, michaljedro commented on app/scss/_section-offerts.scss
> +i {
i didn't know it. i applied your comments to my code.

2020-10-17 20:34 UTC, michaljedro commented on app/scss/_section-offerts.scss
> +.fa-list {
ok. i did it

2020-10-22 19:59 UTC, pawel-schmidt requested changes

2020-10-22 19:59 UTC, pawel-schmidt commented on index.html
> +        <i class="fas fa-check fa-7x"></i>
Does it make sense to give `font-size` class to the parent if you are using `fa-7x` for the icon? 🤔 I'd remove this `font-size` class totally.

2020-10-22 20:01 UTC, pawel-schmidt commented
Please resolve merge conflicts as well.

2020-11-03 19:53 UTC, pawel-schmidt approved these changes

2020-11-03 20:01 UTC, pawel-schmidt approved these changes

2020-11-03 20:02 UTC, merged