Zj1.5/form to apply
michaljedro/zaplanujJedzonko pull request #8
Opened 2020-10-24 10:30 UTC by michaljedro

2020-10-29 09:16 UTC, pawel-schmidt requested changes
In general, I think the section you were working on doesn't look like the one on the design:

Your section:
![image](https://user-images.githubusercontent.com/2522029/97546985-7f51f600-19cd-11eb-942f-4ad31584c4bc.png)

Design:
(sorry, I can't provide a screenshot because I don't have access right now 😢)

2020-10-29 09:16 UTC, pawel-schmidt commented on app/scss/_form-to-apply.scss
> +    min-width: 80%;
I think this one is not needed.

2020-10-29 09:16 UTC, pawel-schmidt commented on app/scss/_form-to-apply.scss
> +    min-width: 80%;
I think this one is not needed.

2020-10-29 09:16 UTC, pawel-schmidt commented on app/scss/_form-to-apply.scss
> +    font-size: 50px;
Why so big font here?

2020-10-29 09:16 UTC, pawel-schmidt commented on app/scss/_form-to-apply.scss
> +    margin-right: none;
Wrong `none` value.

2020-10-29 09:16 UTC, pawel-schmidt commented on app/scss/_form-to-apply.scss
> +    margin-left: none;
Wrong `none` value.

2020-10-29 09:16 UTC, pawel-schmidt commented on app/scss/_form-to-apply.scss
> +.form__box-button {
I think you may add `cursor: pointer;` for better UX.

2020-10-29 09:16 UTC, pawel-schmidt commented on index.html
> +  <div class="bgc_form">
For better semantic, you might use `section` tag instead of `div` here. Also, I'd add some more meaningful name for this section because `form` is very general - at first glance, you don't know what type of form it is: contact form, newsletter subscription, login…

This comment applies also to previous sections.

2020-10-29 09:16 UTC, pawel-schmidt commented on index.html
> +      <div class="form__wrapper">
IMO when looking at styles applied to these both classes one of them seems to be redundant - you may merge their styles.

2020-11-08 19:40 UTC, michaljedro commented on index.html
> +          <p>
ok. i see it.

2020-11-08 19:41 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +        // min-width: 80%;
done ;)

2020-11-08 19:43 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +    min-width: 80%;
i removed this one

2020-11-08 19:51 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +    font-size: 50px;
i did smaller one. i had not got a size conception  .

2020-11-08 19:53 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +    margin-right: none;
i chagned to 0

2020-11-08 20:18 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +    margin-left: none;
ok. i changed it.

2020-11-08 20:25 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +.form__box-button {
ok

2020-11-09 19:54 UTC, michaljedro commented on index.html
> +  <div class="bgc_form">
ok. i changes everything for contact. I changed the divs into section for more meaningful form

2020-11-16 18:22 UTC, pawel-schmidt requested changes

2020-11-16 18:22 UTC, pawel-schmidt commented on app/scss/_form-to-apply.scss
> +.bgc_contact {
```suggestion
.contact_bgc {
```

2020-11-19 21:49 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +.bgc_contact {
ok. i chagned it

2020-11-19 21:49 UTC, michaljedro commented on index.html
> +      <div class="form__wrapper">
ok. i rewritten that class

2020-12-01 21:24 UTC, michaljedro commented on app/scss/_form-to-apply.scss
> +    min-width: 80%;
i would like to talk about this one, because not eveything is clear for me

2020-12-02 13:25 UTC, pawel-schmidt approved these changes

2020-12-02 18:54 UTC, merged